/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

public class App {


    public static void main(String[] args) {
      int[] array= {8,4,23,42,16,15};
      QuickSort quickSort=new QuickSort();
      System.out.println(quickSort.quickSort(array,0,array.length-1)[1]);
    }
}
