/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashMap;

import java.util.HashMap;

public class App {


    public static void main(String[] args) {
      System.out.println(new Hashmap().hashMap("hello you one hello hello hello i love you and hello you "));

    }
}
