/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashMap;

public class App {


    public static void main(String[] args) {
      System.out.println(new Hashmap().repeatedWord("  a d s e r s a, "));
    }
}
