/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashMap;

public class App {


    public static void main(String[] args) {
      System.out.println(new Hashmap().repeatedWord(" all name, my name is noor, hello is"));
    }
}
