/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

public class App {




    public static void main(String[] args) {
      int array[]={8,4,23,42,16,15};
      int result[]= insertionSort(array);
      for (int i = 0; i < result.length; i++) {
        System.out.println(result[i]);
      }
    }

    public static int[] insertionSort(int[] arr){

      for (int i = 1; i < arr.length; i++) {
        int j=i-1;
        int temp = arr[i];
        while (j>=0 && temp<arr[j]){
          arr[j+1]=arr[j];
          j=j-1;
        }
        arr[j+1]=temp;
      }
      return arr;
    }


}
