/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

import java.sql.Array;
import java.util.Arrays;

public class App {


    public static void main(String[] args) {
      int[] array ={8,4,23,42,16,15};
     int[] result =mergeSort(array);
      for (int i = 0; i < result.length; i++) {
        System.out.println(result[i]);
      }
    }

    public static int[] mergeSort(int[] arr){

      int n=arr.length;

      if(n>1){
        int mid = n/2;
       int[] left = Arrays.copyOfRange(arr,0,mid);
        int[] right=Arrays.copyOfRange(arr,mid,n);

        mergeSort(left);
        mergeSort(right);
       merge(left,right,arr);

        }
      return arr;
      }

      public static int[] merge(int[] left,int[] right ,int[] arr){
        int i=0;
        int j=0;
        int k=0;

        while (i<left.length && j<right.length){
          if(left[i]<= right[j]){
            arr[k]=left[i];
            i++;
          }else{
            arr[k]=right[j];
            j++;
          }
          k++;
        }

        if(i==left.length){
          for (int l = j; l < right.length; l++) {
            arr[k] = right[l];
            k++;
          }
        }

        if(j==right.length){
          for (int r = i; r < left.length; r++) {
            arr[k] = left[r];
            k++;
          }
        }

    return arr;
    }
}


