/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;


import java.util.ArrayList;

public class App {


    public static void main(String[] args) {

      Graph graph=new Graph();

      ArrayList<Node > root1=new ArrayList<>();
      ArrayList<Node > root2=new ArrayList<>();
      Node node1=new Node("C");
      Node node2=new Node("D");
      Node node3=new Node("A");


      graph.graphsNode.put(node1,root1);
      graph.graphsNode.put(node2,root2);



      graph.addEdge(node1,node2);
//      System.out.println(graph.graphsNode);
      System.out.println(graph.getNodes());

//      System.out.println(graph.getNeighbors(node1));

    }
}
