/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;


import org.junit.Test;

import static junit.framework.TestCase.assertEquals;

public class AppTest {
    // Test the add function to Hash table .
    @Test
    public void testAddingToHashTable(){
      HashTable hashTable=new HashTable();
      hashTable.add("abc",123);
      System.out.println(hashTable.array[hashTable.hash("abc")].value);
      assertEquals(123,hashTable.array[hashTable.hash("abc")].value,0.0);
    }

    // Test the get function from the hash table .
  @Test
  public void testGettingFunction(){
      HashTable hashTable= new HashTable();
      hashTable.add("ab",8);
      hashTable.add("cd",9);
      assertEquals(9,hashTable.get("cd"),0.0);
  }

    // Test Hash function .
  @Test
  public void testHashingFunction(){
      HashTable hashTable=new HashTable();
      String key="a";
      int hashResult=(int)key.charAt(0)/29;
      assertEquals(hashResult,hashTable.hash("a"));
  }
  // Test Contains function .
  @Test
  public void testContainsFunction(){
      HashTable hashTable =new HashTable();
    hashTable.add("ab",1);
    hashTable.add("bc",2);
    assertEquals("this function return true if its the key found",true,hashTable.contains("bc"));
    assertEquals("this function return true if its the key found",false,hashTable.contains("c"));
  }
}
