/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.binary.search;

public class App {


    public static void main(String[] args) {

      int[] arr={131, -82, 0, 27, 42, 68, 179};
      System.out.println(binarySearch(arr,42));

    }

  public static int binarySearch(int[]arr,int n){
    int l=0;
    int r=arr.length;

    while (true){
      int middle=(int)Math.ceil((l+r-1)/2.0);
      if(n==arr[middle]){
        return middle;
      }else if(n>arr[middle]){
        l=middle;

      }else if(n<arr[middle]) {
        r = middle;
      }
      if(l==arr.length-1||r==0){
        return -1;
      }
    }
  }
}
