/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashMapLeftJoin;

import java.util.ArrayList;
import java.util.HashMap;

public class App {

    public static void main(String[] args) {


      HashMap<String,ArrayList<String>> hashMap1=new HashMap<>();
      ArrayList<String > list=new ArrayList<>();
      list.add("enamored");
      hashMap1.put("fond",list);
      ArrayList<String > list2=new ArrayList<>();
      list2.add("anger");
      hashMap1.put("wrath",list2);
      ArrayList<String > list3=new ArrayList<>();
      list3.add("employed");
      hashMap1.put("diligent",list3);
      ArrayList<String > list4=new ArrayList<>();
      list4.add("garb");
      hashMap1.put("outfit",list4);
      ArrayList<String > list5=new ArrayList<>();
      list5.add("usher");
      hashMap1.put("guide",list5);

        HashMap<String, String > hashMap2=new HashMap<>();
      hashMap2.put("fond","averse");
      hashMap2.put("wrath","delight");
      hashMap2.put("diligent","idle");
      hashMap2.put("guide","follow");
      hashMap2.put("flow","jam");

      HashMapLeftJoin hashMapLeftJoin=new HashMapLeftJoin();
      System.out.println(hashMapLeftJoin.leftJoin(hashMap1,hashMap2));;

    }
}
