/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reverseArray;

import java.sql.Array;

public class App {
    public static int[]  reverseArray(int[] arr) {
      int retArr[]=new int[arr.length];
      for (int i=0 ; i<arr.length ; i++)
      {
        retArr[i]=arr[arr.length-i-1];
      }
      return retArr;
    }
  public static int array[] = {123,56,81,52,563,5674};

    public static void main(String[] args) {
      int arr[]=reverseArray(array);
      for(int i=0;i<arr.length;i++){
        System.out.print(arr[i]+"\t");
      }
    }
}
