/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.insert.shift;

public class App {

    public static void main(String[] args) {
      int [] x={1,2,4,5,90};
      x=insertShiftArray(x,8);
      for (int i = 0; i < x.length; i++) {
        System.out.println(x[i]);
      }
    }
    public static int[] insertShiftArray(int[] arr ,int value){
      int[] newArr=new int[arr.length+1];
      int midIndex=(int)Math.ceil(arr.length/2.0);
      for (int i = 0; i < arr.length; i++) {
        newArr[i]=arr[i];
      }
      for (int i = arr.length; i >midIndex ; i--) {
        newArr[i] = arr[i - 1];
      }
      newArr[midIndex]=value;
      return newArr;
    }
}
