/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
   @Test
  public void testMergeSortFunction(){
     int[] array ={8,4,23,42,16,15};
     int[] resultArr={4,8,15,16,23,42};
     assertArrayEquals(resultArr,App.mergeSort(array));
   }

}
